name: Add Issue to Jira Board On new Dependabot PR's

on:
  push:
    branches:
      - ND-271-spike-dependabot-ticket-auto-creation-in-jira
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  call-workflow-dependabot-pr-to-jira:
    uses: ministryofjustice/nvvs-devops-github-actions/.github/workflows/dependabot-pr-to-jira.yml@ND-271-spike-dependabot-ticket-auto-creation-in-jira
    secrets:
      TECH_SERVICES_JIRA_URL: ${{ secrets.TECH_SERVICES_JIRA_URL }}
      TECH_SERVICES_JIRA_EMAIL: ${{ secrets.TECH_SERVICES_JIRA_EMAIL }}
      TECH_SERVICES_JIRA_TOKEN: ${{ secrets.TECH_SERVICES_JIRA_TOKEN }}

