on:
  workflow_call:
    secrets:
      TECH_SERVICES_JIRA_URL:
        description: 'jira URL passed from the caller workflow'
        required: true
      TECH_SERVICES_JIRA_EMAIL:
        description: 'email address passed from the caller workflow'
        required: true
      TECH_SERVICES_JIRA_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  check-open-prs:
    runs-on: ubuntu-latest
    name: Create or Update Jira Ticket
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.TECH_SERVICES_JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.TECH_SERVICES_JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.TECH_SERVICES_JIRA_TOKEN }}

      - name: List open Dependabot PRs on main branch
        id: list-prs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr list --repo ${{ github.repository }} --base main --json number,title,headRefName,author > pr_list.json
          if ! jq -e . pr_list.json > /dev/null 2>&1; then
            echo "Invalid JSON output from gh pr list"
            cat pr_list.json
            exit 1
          fi

      - name: Format PRs for Jira ticket Description
        id: format-prs
        run: |
          PR_DESCRIPTION=$(jq -r '.[] | "- PR Number: \(.number)  Title: \(.title)  Branch: \(.headRefName)  URL: https://github.com/${{ github.repository }}/pull/\(.number)\n"' pr_list.json | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "PR_DESCRIPTION=$PR_DESCRIPTION" >> $GITHUB_ENV


      - name: Get Jira Issues with Dependabot Label in Project ND
        env:
          JIRA_URL: ${{ secrets.TECH_SERVICES_JIRA_URL }}
          JIRA_API_TOKEN: ${{ secrets.TECH_SERVICES_JIRA_TOKEN }}
          JIRA_USERNAME: ${{ secrets.TECH_SERVICES_JIRA_EMAIL }}
        run: |
          echo "Searching for issues with the 'dependabot' label in project 'ND'..."

          # Define JQL query to find issues with the 'dependabot' label in the 'ND' project
          JQL_QUERY='project="ND" AND labels="dependabot"'

          # Make API request to Jira to search for issues with the given label in the 'ND' project
          response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
            -X GET \
            -H "Content-Type: application/json" \
            "$JIRA_URL/rest/api/2/search?jql=$JQL_QUERY")

          # Include new curl POST request for Jira autocomplete data
          curl --request POST \
            --url 'https://dsdmoj.atlassian.net/rest/api/3/jql/autocompletedata' \
            --user "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "includeCollapsedFields": true,
              "projectIds": ["ND"]
            }'

          # Extract all issue keys from the response (loop through all issues)
          issue_keys=$(echo $response | jq -r '.issues[].key')

          if [ -z "$issue_keys" ]; then
            echo "No issues found with the 'dependabot' label in project 'ND'."
          else
            # Iterate over all found issue keys and update each one
            echo "Found Jira issue(s) with dependabot label:"
            echo "ISSUE_KEYS=$ISSUE_KEYS" >> $GITHUB_ENV
            for issue_key in $issue_keys; do
              echo "Updating description of issue $issue_key..."

              # Prepare the updated description (you can customize the description text)
              NEW_DESCRIPTION="This issue has been updated due to Dependabot's automated changes."

              # Use Jira API to update the description of each found issue
              update_response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
                -X PUT \
                -H "Content-Type: application/json" \
                -d '{
                      "fields": {
                        "description": "'"$NEW_DESCRIPTION"'"
                      }
                    }' \
                "$JIRA_URL/rest/api/2/issue/$issue_key")

              # Check the response for success (this part can be customized based on your needs)
              echo "Description updated for issue $issue_key."
            done
          fi

      - name: Log created or updated issue
        run: |
          if [ -n "${{ env.ISSUE_KEYS }}" ]; then
            echo "Issue ${{ env.ISSUE_KEYS }} was created or updated"
          else
            echo "Failed to create or update issue"
            exit 1
          fi

      - name: Comment on GitHub
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const prs = JSON.parse(fs.readFileSync('pr_list.json', 'utf8'));
            prs.forEach(pr => {
              github.rest.issues.createComment({
                issue_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `${{ env.ISSUE_KEYS }} created or updated on Jira board`
              });
            });

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ env.issue_key }}
          transition: "Backlog"
        continue-on-error: true