on:
  workflow_call:
    secrets:
      TECH_SERVICES_JIRA_URL:
        description: 'jira URL passed from the caller workflow'
        required: true
      TECH_SERVICES_JIRA_EMAIL:
        description: 'email address passed from the caller workflow'
        required: true
      TECH_SERVICES_JIRA_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  check-open-prs:
    runs-on: ubuntu-latest
    name: Create Jira Ticket
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.TECH_SERVICES_JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.TECH_SERVICES_JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.TECH_SERVICES_JIRA_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: 'ND'
          issuetype: 'Story'
          summary: 'Dependabot PRs for ${{ github.repository_url }}'
          description: |
            {panel}
            *Dependabot PRs:*
            $(cat dependabot-prs.json | jq -r '.[] | "- PR #\(.number): \(.title) (branch: \(.head))"')
            {panel}

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"

      - name: Comment on GitHub
        uses: actions/github-script@v7
        with:
            script: |
              prs=$(cat dependabot-prs.json)
              for pr in $(echo "${prs}" | jq -c '.[]'); do
                number=$(echo "${pr}" | jq -r '.number')
                github.rest.issues.createComment({
                  issue_number: number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '${{ steps.create.outputs.issue }} created on Jira board and transitioned to backlog'
                })
              done

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "Backlog"

