name: List All Pull Requests
on:
  workflow_dispatch: # Trigger manually
permissions:
  pull-requests: read
jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
      - name: List all pull requests
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls" > prs.json
          echo "Fetched pull requests:"
          cat prs.json